### ISSUE TITLE
can you still download this in September 2024?

### ISSUE THREAD

**Issue by Laroi4life** [djlorenzouasset/Athena#21] opened 2024-09-22 01:00 UTC
i was wondering if you can still download this is September 2024 because i just downloaded carbon just today and i dont know how to get skins in carbon

**Comment by djlorenzouasset** [comment] 2024-09-22 06:34
atm, Cranium and Carbon are in a state of non functionality since v30.10 (caused by the new anticheat system). You can still get skins on old versions of the game.

**Comment by djlorenzouasset** [comment] 2024-09-23 23:43
closing this issue.

**Closed by djlorenzouasset** 2024-09-23 23:43 UTC
Labels: question
